### ISSUE TITLE
Add more developer documentation

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#128]
**Topics to add:**
- [x] Different events and how to use them.
- [x] Basic guide for getting the AreaShop instance and manipulating regions.
- [x] Update modules/classes overview page, maybe only certain classes.
- [x] Readme.md per module in the repository
